-- MySQL Script generated by MySQL Workbench
-- Wed Jul 29 10:45:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartbase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartbase` DEFAULT CHARACTER SET utf8 ;
USE `smartbase` ;

-- -----------------------------------------------------
-- Table `smartbase`.`PUESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartbase`.`PUESTO` (
  `ID_puesto` INT NOT NULL,
  `Tipo_puesto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartbase`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartbase`.`ROLES` (
  `ID_roles` INT NOT NULL,
  `Tipo_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartbase`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartbase`.`USUARIOS` (
  `ID_usuario` INT NOT NULL,
  `Nombre_usuario` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `PUESTO_ID_puesto` INT NOT NULL,
  `ROLES_ID_roles` INT NOT NULL,
  PRIMARY KEY (`ID_usuario`, `PUESTO_ID_puesto`, `ROLES_ID_roles`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  INDEX `fk_USUARIOS_PUESTO_idx` (`PUESTO_ID_puesto` ASC) VISIBLE,
  INDEX `fk_USUARIOS_ROLES1_idx` (`ROLES_ID_roles` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_PUESTO`
    FOREIGN KEY (`PUESTO_ID_puesto`)
    REFERENCES `smartbase`.`PUESTO` (`ID_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_ROLES1`
    FOREIGN KEY (`ROLES_ID_roles`)
    REFERENCES `smartbase`.`ROLES` (`ID_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartbase`.`PERMISOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartbase`.`PERMISOS` (
  `ID_permiso` INT NOT NULL,
  `Tipo_permiso` VARCHAR(60) NOT NULL,
  `Desc_permiso` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`ID_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartbase`.`PERMISOS_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartbase`.`PERMISOS_ROLES` (
  `ROLES_ID_roles` INT NOT NULL,
  `PERMISOS_ID_permiso` INT NOT NULL,
  PRIMARY KEY (`ROLES_ID_roles`, `PERMISOS_ID_permiso`),
  INDEX `fk_ROLES_has_PERMISOS_PERMISOS1_idx` (`PERMISOS_ID_permiso` ASC) VISIBLE,
  INDEX `fk_ROLES_has_PERMISOS_ROLES1_idx` (`ROLES_ID_roles` ASC) VISIBLE,
  CONSTRAINT `fk_ROLES_has_PERMISOS_ROLES1`
    FOREIGN KEY (`ROLES_ID_roles`)
    REFERENCES `smartbase`.`ROLES` (`ID_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLES_has_PERMISOS_PERMISOS1`
    FOREIGN KEY (`PERMISOS_ID_permiso`)
    REFERENCES `smartbase`.`PERMISOS` (`ID_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
